### ISSUE TITLE
Create installation instructions for installing agrisufia from github

### ISSUE THREAD

**Issue by elrayle** [cul-it/agrisufia#3]
Create installation instructions for installing code from this repository onto a DEV VM. These instructions should be compatible with the [instructions for installing from scratch](https://confluence.cornell.edu/x/3IiTEQ).

**Comment by elrayle** [comment]
agrisufia install instructions: https://confluence.cornell.edu/x/d4GcEg

Needs verification.  Tim, do you want to try these instead of the from scratch instructions?

**Comment by tworrall** [comment]
I was planning to follow the instructions that are Confluence as that's what we discussed.

Tim

**Comment by elrayle** [comment]
The agrisufia instructions shares all the same verification steps with the from scratch instructions.  The part that is different is the installation of sufia code which is drawn from cul-it/agrisufia instead of project-hydra/sufia.  Tim, I'll touch base with you this afternoon to see where you are and whether switching instruction sets makes sense.
